spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: SEU_CLIENT_ID_AQUI
            client-secret: SEU_CLIENT_SECRET_AQUI
            scope: email,profile
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/quiz_biblico_db?authSource=admin

# Configuração JWT
jwt:
  secret: chave_secreta_muito_segura_com_pelo_menos_32_caracteres_123456
  expiration: 86400000 # 24 horas em milissegundos

# Configuração de logging
logging:
  level:
    br.com.devluisoliveira: DEBUG
    org.springframework.data.mongodb: INFO
    org.springframework.security: INFO

# Configuração do servidor
server:
  port: 8080
  servlet:
    context-path: /