spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: SEU_CLIENT_ID
            client-secret: SEU_CLIENT_SECRET
            scope: email,profile
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/quiz_biblico_db?authSource=admin
    redis:
      host: localhost
      port: 6379
      password: redis123